services:
  - type: web
    name: pdf-to-xml-converter
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/pdf-to-xml-converter/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
